subscribers:

  camera_reading:
    topic: /qingzhou/camera_link/image_raw  #订阅图像话题
    # topic: /robot3/camera_link/image_raw
    queue_size: 1

actions:
  
  camera_reading:
    name: /darknet_ros/check_for_objects

publishers:
  #发布话题
  object_detector:
    topic: /darknet_ros/found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /darknet_ros/bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /darknet_ros/detection_image
    queue_size: 1
    latch: true

image_view:

  enable_opencv: true
  wait_key_delay: 1
  enable_console_output: true
