yolo_model:

  config_file:
    name: yolov2-tiny_rxz.cfg
  weight_file:
    name: yolov2-tiny_3840000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - person
      - car
      - traffic cone
      - trash can
      - tree
